### ISSUE TITLE
suggest about learn_rate or steps

### ISSUE THREAD

**Issue by jihobak** [nethsix/gentle_tensorflow#10]
@nethsix Thanks for your tutorial :)

current

``` python
steps = 100
learn_rate = 0.0000001
```

I think it is better to adjust learn_rate or steps in the code because beginner who is not familiar with machine learning concept yet have question about value of W, b. 

and what about adding the cost? I think it will show the how the cost is changed
ex) print("Cost: {0}".format(sess.run(cost, feed_dict=feed)))

**Comment by nethsix** [comment]
@jihobak Sorry for the late reply. I agree that the code should just run correctly without any tuning!  I've update the code, please let me know if it works now.

Thanks for your good suggestion about adding Cost. I've also added that.

Please refer to the code update: https://github.com/nethsix/gentle_tensorflow/pull/11

Thanks for helping make things better!

**Comment by jihobak** [comment]
Thanks  👍
